### ISSUE TITLE
KillSwitchEvent

### ISSUE THREAD

**Issue by midascodebreaker** [vandernorth/NecroBot.GUI#101]
I check the latest version and it has this KillSwitch...
```
"UseKillSwitchCatch": true,
    "CatchErrorPerHours": 40,
    "CatchEscapePerHours": 40,
    "CatchFleePerHours": 40,
    "CatchMissedPerHours": 40,
    "CatchSuccessPerHours": 40
```

I hope we can add a killswitch for the maximum no of pokestop to spin/day
and no of pokemon catch/day...

**Comment by RuneMykle** [comment]
Unzip this in your Gui folder and start the bot with the file **NecroBot.GUI.BanSafe.bat** instead of NecroBot.GUI.exe

It will start your Necrobot.GUI and also open a terminal window that shows your count of catches and pokestops and exit the bot when either 950 pokemons or 1900 pokestops. It also creates a "Old" catalogue in your logs folder and moves your logfiles there.

[NecroBot.GUI.BanSafe.bat.zip](https://github.com/vandernorth/NecroBot.GUI/files/424677/NecroBot.GUI.BanSafe.bat.zip)

**Comment by tmathura** [comment]
@RuneMykle I modified your bat a bit, so it logs the counts to a text file and also I made it into a exe. You guys can just drop the exe where NecroBot.GUI is. How do I upload it?

**Comment by RuneMykle** [comment]
Zip it and upload it :) :+1:

**Comment by tmathura** [comment]
I am trying that, it says "Unfortunately, we don’t support that file type.". And the file is zipped

**Comment by RuneMykle** [comment]
yeah, well.. no need to make it an exe really.. these are open source projects :)

**Comment by tmathura** [comment]
I even tried zipping the bat and uploading and it does not want to work :-(

**Comment by tmathura** [comment]
[NecroBot.GUI.BanSafe.bat](https://github.com/vandernorth/NecroBot.GUI/files/425730/NecroBot.GUI.BanSafe.bat)

**Comment by vandernorth** [comment]
I'll add the .bat to the next version :-)

**Comment by tmathura** [comment]
@vandernorth here is my latest version of the bat, it should fix the time stamp when I was creating the count file and old log folder. You can just test it to see if you are happy :+1:  just rename it to .bat. For some reason I can upload zips
[NecroBot.GUI.BanSafe.txt](https://github.com/vandernorth/NecroBot.GUI/files/428210/NecroBot.GUI.BanSafe.txt)
