### ISSUE TITLE
Cannot start NecroBot.GUI.exe

### ISSUE THREAD

**Issue by ValorRed** [vandernorth/NecroBot.GUI#104]
It is closing immediately. Checked .Net installed properly. Old version 0.4.2 working properly
![guiproblem](https://cloud.githubusercontent.com/assets/20829876/17775626/1aa611fa-6527-11e6-92b3-740ed76fdd13.png)
![ms net install](https://cloud.githubusercontent.com/assets/20829876/17775628/1e1b0dfe-6527-11e6-9014-9d5f3be18177.png)

**Comment by Wise01** [comment]
Did you restart your computer after installing .NET Framework 4.6.2?
If you just installed .NET Framework 4.6.2 restarting might help.

**Comment by TLBM** [comment]
The same here.
Restarted PC after .NET-install und only copied the auth.conf
Win 8.1 Pro 64bit German

**Comment by ValorRed** [comment]
Tried both. The config is not having problem. I copied back the older version 0.4.2, the config is working file. Config file is attached here. Please help to investigate. 
Or, If you can provide a link to older release. I can help to try between 0.4.2 & 0.5.0, which one starts

 causing problem.

**Comment by jimmyxXx** [comment]
Having same problem. The problem is when there is a config issue the app just shuts down without any diagnostic message as to what the issue is.
I let the app generate default auth.json and config.json. I then modified auth.json to use my username, password, and device id. I copied the first few fields from the new config.json into my working config.json (working with necrobotui v0.4.2). v0.5 still just shuts down without any error messages. Makes it kind of hard to figure out what's wrong.

**Comment by ValorRed** [comment]
jimmyxXx , you are genius. Here is the solution:
1. Start the exe without any config
2. Modify the new created auth.json and config.json with your own settings.

You cannot use the old config files, it's different json formats. Seems the new Necro version changed the data structure design. It tries to regroup settings into objects.

**Comment by jimmyxXx** [comment]
Well, I'm not such a genius, I still can't get it to start. I just change auth.json, use the default generated config.json, and still doesn't start. @ValorRed , can you post your auth.json (clear your username & password) and your config.json?
