### ISSUE TITLE
captcha in game

### ISSUE THREAD

**Issue by hanncreator** [vandernorth/NecroBot.GUI#149]
Description:
It seems that PokemonGo is planning to insert captcha in the game:
http://pokemongohub.net/captcha-game-pokemon-go-bots-trackers/

Do you guys know some way to work around this problem? For instance, come to my mind to send all images on telegram (so create a telegram bot that sends the captcha images) and manually choose the correct ones.. 
Don't know!

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by raymonders** [comment]
In my head, what i see is basically using an emulator or something alongside the game? so that we see what's going on ingame as well?

for example we can toggle between "Map" and "Screen". when the bot face a captcha, it pauses and a popup alert comes up, so we toggle to the "screen" window and answer the captcha. 

it sounds very complicated though, basically needing to run the game at the same time as the bot

**Comment by golgolak** [comment]
or have the bot send the captcha via telegram and we send the answer back via telegram as well...

**Comment by vandernorth** [comment]
Once the captcha is there it'll hopefully be implemented by necrobot. If necessary I'll implement that as well.

**Comment by EugeneTkachenko** [comment]
open the issue once again. You know why... all bots are stopping working once found a Pokestop with incorrect data and the game with ask you to reenter captcha and BOM! no any bot can do it so far....
