### ISSUE TITLE
bot wont open

### ISSUE THREAD

**Issue by veid71** [vandernorth/NecroBot.GUI#3]
Initializing NecroBot logger at time 8/10/2016 7:09:21 PM...

thats all i get when i try to run the bot it doesnt open up

actually it only opens up the first time you run the bot any time after that it wont

**Comment by vandernorth** [comment]
Any (error)messages when it wont open?

**Comment by veid71** [comment]
Nope just refuses to open when you click it

**Comment by RuneMykle** [comment]
Your "GetSniperInfoFromPokezz": setting is?

**Comment by veid71** [comment]
Hmmm I'm not sure I'm not at home right now but I think I had it set to false

**Comment by RuneMykle** [comment]
It's sat as "True" as default (Which should be set to false as default as is it now btw), so if you're sniping, make sure it's not true then try again.

I'm pretty sure your problem is related to your config file though, so maybe try to see if you can run a standard necrobot 0.8.5 with the config file from this gui setup.

**Comment by RuneMykle** [comment]
Yeah, several are reporting this.

Setting in config needs to be fixed to:

"GetSniperInfoFromPokezz": false,

**Comment by veid71** [comment]
Hmmm alright I'll try it I know it doesn't work right now but I don't see why that would cause it to crash... other than flooding it with the false information or the connections it tries to make I suppose

**Comment by vandernorth** [comment]
The bot also opens and then almost immediately closes when you have invalid auth.json or invalid config.json or invalid credentials in auth.json
