### ISSUE TITLE
A more ban-proof method suggestion.

### ISSUE THREAD

**Issue by abhay4sengars** [vandernorth/NecroBot.GUI#63]
I would love to have a terminate bot sort of thing before the threshold of Pokemon/day and Pokestops/day is reached and also if we can set the amount. Would love this feature.

**Comment by RogueMaster** [comment]
If we could schedule a back up auth.json or maybe 2 other auth.json then we could rotate accounts on a single bot so the same bot isn't online for 12+ hrs straight.

**Comment by RogueMaster** [comment]
Got these from Turingbot... these would be nice to see implemented...
– PokeStop Tracker (doesn’t go over 999 in a day. MAX 1000 per day)
– Pokemon Capture Tracker (catch up to 2000 per day, set to 1500)
– Kill switch (Shuts down the bot when you get to those numbers OR SWITCHES TO ANOTHER ACCOUNT?)

**Comment by midascodebreaker** [comment]
i was looking for that type of function, maybe they can add it here...
since going for 50k pokestops is impossible...
if you set the max limit to a more human like limit same with pokemon catch...
and run for 12 hrs a day... 
Niantic has no idea of what really is going on ,
unless you bang a GYM with a level 40 and got reported

**Comment by vandernorth** [comment]
I like the idea of rotating multiple auth.json's (but not everybody might have multiple accounts). 
Schedule switches are nice as well...  I'll see what I can do..

**Comment by RuneMykle** [comment]
Yeah, this is a great idea! I think most botters have more than one account these days.

**Comment by carlos0202** [comment]
Also please, in the next release is it possible to update the core of the Necrobot to the lastest version of the new fork. They have implemented the walkingSpeedVariance and some other good things. And all the suggestions that we should follow to avoid the ban hammer. 4 of my 8 accounts are dead now and i don't want all of them to die. Thanks in advance.

**Comment by RuneMykle** [comment]
Would love to see this in the gui. Seems to be the main factors of banning these days.

There's counters out there that keeps track of the logs, but then I've got to use another bot without this gui. And this gui is starting to rock so I dont wanna do that! :)

I realize that it's some work, but would give you loads of happy customers these days :)

And with such features I bet you soon could rename your project to VanDerBot! :)

> Got these from Turingbot... these would be nice to see implemented...
– PokeStop Tracker (doesn’t go over 999 in a day. MAX 1000 per day)
– Pokemon Capture Tracker (catch up to 2000 per day, set to 1500)
– Kill switch (Shuts down the bot when you get to those numbers OR SWITCHES TO ANOTHER ACCOUNT?)
-Roguemaster

**Comment by RuneMykle** [comment]
Unzip this in your Gui folder and start the bot with the file NecroBot.GUI.BanSafe.bat instead of NecroBot.GUI.exe

It will start your Necrobot.GUI and also open a terminal window that shows your count of catches and pokestops and exit the bot when either 950 pokemons or 1900 pokestops. It also creates a "Old" catalogue in your logs folder and moves your logfiles there.

[NecroBot.GUI.BanSafe.bat.zip](https://github.com/vandernorth/NecroBot.GUI/files/424826/NecroBot.GUI.BanSafe.bat.zip)

But yeah, would be way better to get this in the gui with options on the numbers.

**Comment by vandernorth** [comment]
Haha nice batch file! But there are settings in the new necrobot right? In the SoftBanSettings section?

`  "SoftBanSettings": {
    "FastSoftBanBypass": false,
    "UseKillSwitchCatch": true,
    "CatchErrorPerHours": 40,
    "CatchEscapePerHours": 40,
    "CatchFleePerHours": 40,
    "CatchMissedPerHours": 40,
    "CatchSuccessPerHours": 40
  },`

**Comment by RuneMykle** [comment]
Yeah, but the point is to close it before you get flagged by those error messages :) 

The word on the street says 1000 pokemons or 2000 pokestops gets you flagged so well. :)

**Comment by vandernorth** [comment]
Its party time when this gets merged into necrobot:
https://github.com/NoxxDev/NecroBot/pull/337

**Comment by vandernorth** [comment]
In combination with this one, even beter: https://github.com/NoxxDev/NecroBot/pull/353 
But we'll have to wait until v0.9.5 probably.

**Comment by RuneMykle** [comment]
oh yeah :) Will be good!
