### ISSUE TITLE
[Issues] Map messing up

### ISSUE THREAD

**Issue by TeachMeSenpai** [vandernorth/NecroBot.GUI#74]
The map messes up if bot goes to snipe... First it shows where the bot is sniping but then it never returns to the normal map

**Comment by vandernorth** [comment]
I've seen this happen, but that was because there were nog LocationUpdates for a while. Same thing on your end or do you have this consequentially?

**Comment by RuneMykle** [comment]
Is it also possible to zoom out the map a tad as default? Most standard configs has the range sat to 1000 meters so maybe make it so that it precisely shows the 1000 radius circle?

Also, is it possible to make it so that Mario (poke trainer) moves around instead of the map moving while having him centered? I think it will drain less of my cpu :)

**Comment by vandernorth** [comment]
Fixed zoomlevel based on walking radius.
